#!/usr/bin/env python3
"""Paired Kuaishou foreground/background heap census for detailed proposals.

Both snapshots must be generated by the same rawheap_translator binary. The
script reports directly measurable shallow-heap facts separately from models
that still require runtime instrumentation.
"""

from __future__ import annotations

import argparse
import collections
import hashlib
import json
import os
import statistics
import subprocess
from dataclasses import dataclass
from typing import Any, Iterable

MIB = 1024 * 1024
HCLASS_NAME = "HiddenClass(NonMovable)"
CONSTANT_POOL_NAME = "ArkInternalConstantPool"
PROFILE_CELL_NAME = "ProfileTypeInfoCell"
PROFILE_TYPE_INFO_NAME = "ArkInternalProfileTypeInfo"
AUX_FIELDS = (
    "EnumCache",
    "ProtoChangeMarker",
    "ProtoChangeDetails",
    "DependentInfos",
)
DEFAULT_VALUE_NAMES = {"Null", "Undefined"}


def sha256_file(path: str) -> str:
    digest = hashlib.sha256()
    with open(path, "rb") as stream:
        for chunk in iter(lambda: stream.read(8 * MIB), b""):
            digest.update(chunk)
    return digest.hexdigest()


def file_record(path: str) -> dict[str, Any]:
    return {
        "path": os.path.abspath(path),
        "bytes": os.path.getsize(path),
        "sha256": sha256_file(path),
    }


def rawheap_protocol(path: str) -> str:
    with open(path, "rb") as stream:
        prefix = stream.read(32)
    token = prefix.split(b"\x00", 1)[0]
    return token.decode("ascii", errors="replace")


def align8(value: int) -> int:
    return (value + 7) & ~7


@dataclass(frozen=True)
class Edge:
    edge_type: str
    label: int | str
    target: int


class Snapshot:
    def __init__(self, path: str) -> None:
        self.path = path
        with open(path, encoding="utf-8", errors="replace") as stream:
            self.data = json.load(stream, strict=False)

        meta = self.data["snapshot"]["meta"]
        self.node_fields = meta["node_fields"]
        self.edge_fields = meta["edge_fields"]
        self.node_field = {name: index for index, name in enumerate(self.node_fields)}
        self.edge_field = {name: index for index, name in enumerate(self.edge_fields)}
        self.node_stride = len(self.node_fields)
        self.edge_stride = len(self.edge_fields)
        self.node_types = meta["node_types"][0]
        self.edge_types = meta["edge_types"][0]
        self.nodes = self.data["nodes"]
        self.edges = self.data["edges"]
        self.strings = self.data["strings"]
        self.node_count = len(self.nodes) // self.node_stride
        self.edge_count = len(self.edges) // self.edge_stride

        self.edge_starts: list[int] = []
        cursor = 0
        for node in range(self.node_count):
            self.edge_starts.append(cursor)
            cursor += self.node_value(node, "edge_count")
        if cursor != self.edge_count:
            raise ValueError(f"edge count mismatch: {cursor} != {self.edge_count}")

    def node_value(self, node: int, field: str) -> int:
        return self.nodes[node * self.node_stride + self.node_field[field]]

    def node_type(self, node: int) -> str:
        return self.node_types[self.node_value(node, "type")]

    def node_name(self, node: int) -> str:
        return self.strings[self.node_value(node, "name")]

    def node_id(self, node: int) -> int:
        return self.node_value(node, "id")

    def self_size(self, node: int) -> int:
        return self.node_value(node, "self_size")

    def native_size(self, node: int) -> int:
        if "native_size" not in self.node_field:
            return 0
        return self.node_value(node, "native_size")

    def outgoing(self, node: int) -> Iterable[Edge]:
        start = self.edge_starts[node]
        count = self.node_value(node, "edge_count")
        for offset in range(count):
            base = (start + offset) * self.edge_stride
            edge_type = self.edge_types[self.edges[base + self.edge_field["type"]]]
            raw_label = self.edges[base + self.edge_field["name_or_index"]]
            label: int | str = raw_label if edge_type == "element" else self.strings[raw_label]
            target = self.edges[base + self.edge_field["to_node"]] // self.node_stride
            yield Edge(edge_type, label, target)

    def metadata(self) -> dict[str, Any]:
        meta = self.data["snapshot"]["meta"]
        return {
            **file_record(self.path),
            "node_count": self.node_count,
            "edge_count": self.edge_count,
            "schema": {
                "node_fields": meta["node_fields"],
                "node_types": meta["node_types"],
                "edge_fields": meta["edge_fields"],
                "edge_types": meta["edge_types"],
            },
        }


def named_target(snapshot: Snapshot, node: int, label: str) -> int | None:
    for edge in snapshot.outgoing(node):
        if edge.label == label:
            return edge.target
    return None


def jshclass_census(snapshot: Snapshot) -> dict[str, Any]:
    hclasses = [node for node in range(snapshot.node_count) if snapshot.node_name(node) == HCLASS_NAME]
    mask_counts: collections.Counter[int] = collections.Counter()
    field_counts: collections.Counter[str] = collections.Counter()

    for hclass in hclasses:
        targets = {edge.label: edge.target for edge in snapshot.outgoing(hclass) if edge.label in AUX_FIELDS}
        mask = 0
        for bit, field in enumerate(AUX_FIELDS):
            target = targets.get(field)
            if target is not None and snapshot.node_name(target) not in DEFAULT_VALUE_NAMES:
                mask |= 1 << bit
                field_counts[field] += 1
        mask_counts[mask] += 1

    candidate_count = len(hclasses) - mask_counts[0]
    gross = 24 * len(hclasses)
    sidecar = 48 * candidate_count
    return {
        "population": len(hclasses),
        "shallow_bytes": sum(snapshot.self_size(node) for node in hclasses),
        "candidate_owner_union": candidate_count,
        "candidate_ratio": candidate_count / len(hclasses) if hclasses else 0.0,
        "field_non_default_counts": {field: field_counts[field] for field in AUX_FIELDS},
        "mask_counts": {str(mask): mask_counts[mask] for mask in range(16)},
        "main_object_gross_bytes": gross,
        "sidecar_cost_bytes": sidecar,
        "net_bytes": gross - sidecar,
        "model": "88 B -> 64 B main object; 48 B TaggedArray(4) per union owner",
        "confidence": "high: exact shallow-size model over surviving HClass nodes",
    }


def layoutinfo_census(snapshot: Snapshot) -> dict[str, Any]:
    layouts: set[int] = set()
    for node in range(snapshot.node_count):
        if snapshot.node_name(node) != HCLASS_NAME:
            continue
        target = named_target(snapshot, node, "Layout")
        if target is not None and snapshot.node_type(target) == "array":
            layouts.add(target)

    old_bytes = 0
    new_bytes = 0
    property_count = 0
    invalid_sizes: collections.Counter[int] = collections.Counter()
    property_histogram: collections.Counter[int] = collections.Counter()
    for layout in layouts:
        size = snapshot.self_size(layout)
        old_bytes += size
        if size < 16 or (size - 16) % 16 != 0:
            invalid_sizes[size] += 1
            continue
        count = (size - 16) // 16
        property_count += count
        property_histogram[count] += 1
        new_bytes += align8(16 + 12 * count)

    if invalid_sizes:
        raise ValueError(f"unexpected LayoutInfo self_size values: {dict(invalid_sizes)}")
    return {
        "unique_layout_count": len(layouts),
        "property_count": property_count,
        "current_shallow_bytes": old_bytes,
        "packed_shallow_bytes": new_bytes,
        "padding_and_header_cost_bytes": new_bytes - 12 * property_count,
        "net_bytes": old_bytes - new_bytes,
        "property_count_histogram": {str(key): value for key, value in sorted(property_histogram.items())},
        "model": "old=16+16N; new=align8(16+12N), evaluated per unique Layout target",
        "confidence": "high: exact per-array shallow-size model over surviving LayoutInfo targets",
    }


def profile_cell_census(snapshot: Snapshot) -> dict[str, Any]:
    by_hclass: collections.Counter[int] = collections.Counter()
    field_edges: dict[str, collections.Counter[str]] = {
        field: collections.Counter() for field in ("Value", "MachineCode", "Handle")
    }
    field_visible_counts: collections.Counter[str] = collections.Counter()
    joint_non_default: collections.Counter[str] = collections.Counter()
    value_handle_joint: collections.Counter[str] = collections.Counter()
    cell_nodes: list[int] = []
    for node in range(snapshot.node_count):
        if snapshot.node_name(node) != PROFILE_CELL_NAME:
            continue
        cell_nodes.append(node)
        visible_fields: dict[str, int] = {}
        target = named_target(snapshot, node, "hclass")
        if target is None:
            raise ValueError("ProfileTypeInfoCell without hclass edge")
        by_hclass[target] += 1
        for edge in snapshot.outgoing(node):
            if edge.label not in field_edges:
                continue
            field = str(edge.label)
            visible_fields[field] = edge.target
            field_visible_counts[field] += 1
            target_name = snapshot.node_name(edge.target)
            if target_name not in {"Undefined", "Hole", "MachineCode", PROFILE_TYPE_INFO_NAME}:
                target_name = "*"
            signature = f"{edge.edge_type}:{snapshot.node_type(edge.target)}:{target_name}"
            field_edges[field][signature] += 1

        machine_code_target = visible_fields.get("MachineCode")
        handle_target = visible_fields.get("Handle")
        value_target = visible_fields.get("Value")
        machine_code_non_default = (
            machine_code_target is not None and snapshot.node_name(machine_code_target) != "Hole"
        )
        handle_non_default = handle_target is not None and snapshot.node_name(handle_target) != "Undefined"
        value_non_default = value_target is not None and snapshot.node_name(value_target) != "Undefined"
        if machine_code_non_default and handle_non_default:
            joint_non_default["machine_code_and_handle"] += 1
        elif machine_code_non_default:
            joint_non_default["machine_code_only"] += 1
        elif handle_non_default:
            joint_non_default["handle_only"] += 1
        else:
            joint_non_default["neither"] += 1
        if value_non_default and handle_non_default:
            value_handle_joint["value_and_handle"] += 1
        elif value_non_default:
            value_handle_joint["value_only"] += 1
        elif handle_non_default:
            value_handle_joint["handle_only"] += 1
        else:
            value_handle_joint["neither"] += 1

    if len(by_hclass) != 3:
        raise ValueError(f"expected 3 ProfileTypeInfoCell HClasses, found {len(by_hclass)}")
    ordered = sorted(by_hclass, key=snapshot.node_id)
    ids = [snapshot.node_id(node) for node in ordered]
    if ids[1] != ids[0] + 2 or ids[2] != ids[1] + 2:
        raise ValueError(f"ProfileTypeInfoCell HClass ids are not sequential: {ids}")
    states = {"cell_0": by_hclass[ordered[0]], "cell_1": by_hclass[ordered[1]], "cell_n": by_hclass[ordered[2]]}
    total = len(cell_nodes)
    stage1_upper = 32 * states["cell_0"]
    return {
        "population": total,
        "shallow_bytes": sum(snapshot.self_size(node) for node in cell_nodes),
        "state_counts": states,
        "state_classification": {
            "rule": "sort the three ProfileTypeInfoCell HClasses by node id; GlobalEnvConstants creates CELL_0, CELL_1, CELL_N in that order",
            "hclass_node_ids": ids,
        },
        "field_edge_counts": {
            field: dict(sorted(counts.items())) for field, counts in field_edges.items()
        },
        "field_no_visible_edge_counts": {
            field: total - field_visible_counts[field] for field in field_edges
        },
        "joint_non_default_counts": {
            key: joint_non_default[key]
            for key in ("neither", "machine_code_only", "handle_only", "machine_code_and_handle")
        },
        "value_handle_joint_counts": {
            key: value_handle_joint[key]
            for key in ("neither", "value_only", "handle_only", "value_and_handle")
        },
        "field_edge_interpretation": (
            "Counts describe serialized outgoing edges only. In these translated snapshots Hole-valued "
            "MachineCode fields have no visible edge, while Undefined Handle and Value fields do; a missing "
            "edge is therefore reported separately and is not assigned a universal runtime value."
        ),
        "stage1_lazy_snapshot_time_upper_bytes": stage1_upper,
        "stage1_candidate_ratio": states["cell_0"] / total if total else 0.0,
        "stage2_24b_existing_stock_net_bytes": 8 * total,
        "stage2_16b_existing_stock_net_bytes": 16 * total,
        "combined_24b_formula_bytes": f"{8 * total} + {24 * total} * e",
        "combined_16b_formula_bytes": f"{16 * total} + {16 * total} * e",
        "model": "stage 1 has no per-absent-cell heap cost; stage 2 removes 8 B or 16 B from each remaining cell",
        "confidence": {
            "existing_stock_layout_cut": "high",
            "lazy_elimination": "medium-low: cell_0 is a snapshot-time structural upper bound, not a lifecycle first-feedback measurement",
        },
    }


def profile_type_info_census(snapshot: Snapshot) -> dict[str, Any]:
    arrays = [
        node for node in range(snapshot.node_count)
        if snapshot.node_name(node) == PROFILE_TYPE_INFO_NAME
    ]
    physical_lengths: list[int] = []
    extra_info_map_edges: collections.Counter[str] = collections.Counter()
    jit_osr_edges: collections.Counter[str] = collections.Counter()

    def record_reserved_edge(counter: collections.Counter[str], target: int) -> None:
        target_name = snapshot.node_name(target)
        if target_name not in {"Undefined", "Hole"}:
            target_name = "*"
        counter[f"{snapshot.node_type(target)}:{target_name}"] += 1

    for array in arrays:
        size = snapshot.self_size(array)
        if size < 16 or (size - 16) % 8 != 0:
            raise ValueError(f"unexpected ProfileTypeInfo self_size: {size}")
        physical_length = (size - 16) // 8
        if physical_length < 5:
            raise ValueError(f"unexpected ProfileTypeInfo physical length: {physical_length}")
        physical_lengths.append(physical_length)
        ic_slot_length = physical_length - 5
        for edge in snapshot.outgoing(array):
            if edge.edge_type != "element":
                continue
            if edge.label == ic_slot_length:
                record_reserved_edge(extra_info_map_edges, edge.target)
            elif edge.label == ic_slot_length + 1:
                record_reserved_edge(jit_osr_edges, edge.target)

    population = len(arrays)
    return {
        "population": population,
        "shallow_bytes": sum(snapshot.self_size(node) for node in arrays),
        "self_size_formula": "16 B TaggedArray header + 8 B * physical_length",
        "physical_length_summary": {
            "minimum": min(physical_lengths) if physical_lengths else None,
            "maximum": max(physical_lengths) if physical_lengths else None,
            "median": statistics.median(physical_lengths) if physical_lengths else None,
            "mode": statistics.mode(physical_lengths) if physical_lengths else None,
            "sum": sum(physical_lengths),
            "unique_values": len(set(physical_lengths)),
        },
        "reserved_length": 5,
        "reserved_tagged_slot_edge_counts": {
            "extra_info_map": dict(sorted(extra_info_map_edges.items())),
            "jit_osr": dict(sorted(jit_osr_edges.items())),
        },
        "reserved_tagged_slot_no_visible_edge_counts": {
            "extra_info_map": population - sum(extra_info_map_edges.values()),
            "jit_osr": population - sum(jit_osr_edges.values()),
        },
        "interpretation": (
            "Reserved tagged slots are identified by physical index: ic_slot_length and "
            "ic_slot_length + 1. The remaining three reserved slots hold primitive fields and "
            "are not inferred from heap-snapshot edges."
        ),
    }


def jitfree_adjacent_layout_census(snapshot: Snapshot) -> dict[str, Any]:
    method_nodes: list[int] = []
    function_template_nodes: list[int] = []
    machine_code_nodes: list[int] = []
    jsfunction_nodes: list[int] = []
    jsfunction_sizes: list[int] = []
    code_slot_states: collections.Counter[str] = collections.Counter()

    for node in range(snapshot.node_count):
        node_name = snapshot.node_name(node)
        node_type = snapshot.node_type(node)
        if node_type == "native" and node_name == "Method":
            method_nodes.append(node)
        elif node_type == "native" and node_name == "ArkInternalFunctionTemplate":
            function_template_nodes.append(node)
        elif node_type == "native" and node_name == "MachineCode":
            machine_code_nodes.append(node)

        visible_fields = {
            str(edge.label): edge.target
            for edge in snapshot.outgoing(node)
            if edge.label in {"RawProfileTypeInfo", "MachineCode", "BaselineCode"}
        }
        if (
            set(visible_fields) != {"RawProfileTypeInfo", "MachineCode", "BaselineCode"}
            or snapshot.node_name(visible_fields["RawProfileTypeInfo"]) != PROFILE_CELL_NAME
        ):
            continue
        jsfunction_nodes.append(node)
        jsfunction_sizes.append(snapshot.self_size(node))
        machine_code_non_default = snapshot.node_name(visible_fields["MachineCode"]) == "MachineCode"
        baseline_code_non_default = snapshot.node_name(visible_fields["BaselineCode"]) == "MachineCode"
        if machine_code_non_default and baseline_code_non_default:
            code_slot_states["machine_code_and_baseline_code"] += 1
        elif machine_code_non_default:
            code_slot_states["machine_code_only"] += 1
        elif baseline_code_non_default:
            code_slot_states["baseline_code_only"] += 1
        else:
            code_slot_states["neither"] += 1

    jsfunction_population = len(jsfunction_nodes)
    return {
        "method": {
            "population": len(method_nodes),
            "shallow_bytes": sum(snapshot.self_size(node) for node in method_nodes),
        },
        "function_template": {
            "population": len(function_template_nodes),
            "shallow_bytes": sum(snapshot.self_size(node) for node in function_template_nodes),
        },
        "machine_code": {
            "population": len(machine_code_nodes),
            "shallow_bytes": sum(snapshot.self_size(node) for node in machine_code_nodes),
        },
        "jsfunction_full_layout": {
            "population": jsfunction_population,
            "shallow_bytes": sum(snapshot.self_size(node) for node in jsfunction_nodes),
            "self_size_summary": {
                "minimum": min(jsfunction_sizes) if jsfunction_sizes else None,
                "maximum": max(jsfunction_sizes) if jsfunction_sizes else None,
                "median": statistics.median(jsfunction_sizes) if jsfunction_sizes else None,
                "mode": statistics.mode(jsfunction_sizes) if jsfunction_sizes else None,
                "unique_values": len(set(jsfunction_sizes)),
            },
            "code_slot_state_counts": {
                key: code_slot_states[key]
                for key in ("neither", "machine_code_only", "baseline_code_only", "machine_code_and_baseline_code")
            },
            "two_code_slot_shallow_bytes": 16 * jsfunction_population,
            "identification_rule": (
                "node has serialized RawProfileTypeInfo, MachineCode, and BaselineCode fields, and "
                "RawProfileTypeInfo targets a ProfileTypeInfoCell; this excludes 40 B FunctionTemplate "
                "nodes and JSApiFunction InternalAccessor placeholders"
            ),
        },
    }


def constantpool_census(snapshot: Snapshot) -> dict[str, Any]:
    pools = [node for node in range(snapshot.node_count) if snapshot.node_name(node) == CONSTANT_POOL_NAME]
    strings: set[int] = set()
    string_edges = 0
    direct_literal_targets: set[int] = set()
    direct_literal_edges = 0
    for pool in pools:
        for edge in snapshot.outgoing(pool):
            if snapshot.node_type(edge.target) == "string":
                strings.add(edge.target)
                string_edges += 1
            if (
                edge.edge_type == "element"
                and snapshot.node_name(edge.target) in {"JSObject", "JSArray"}
            ):
                direct_literal_targets.add(edge.target)
                direct_literal_edges += 1

    direct_literal_target_names = collections.Counter(
        snapshot.node_name(node) for node in direct_literal_targets
    )
    direct_literal_backings: set[int] = set()
    direct_literal_backing_edges = 0
    for target in direct_literal_targets:
        for edge in snapshot.outgoing(target):
            if edge.label in {"Properties", "Elements"} and snapshot.node_type(edge.target) == "array":
                direct_literal_backings.add(edge.target)
                direct_literal_backing_edges += 1

    object_array_nodes = [
        node for node in range(snapshot.node_count)
        if snapshot.node_name(node) in {"JSObject", "JSArray"}
    ]
    object_array_names = collections.Counter(
        snapshot.node_name(node) for node in object_array_nodes
    )
    backings: set[int] = set()
    backing_edges = 0
    for object_node in object_array_nodes:
        for edge in snapshot.outgoing(object_node):
            if edge.label in {"Properties", "Elements"} and snapshot.node_type(edge.target) == "array":
                backings.add(edge.target)
                backing_edges += 1

    vm_roots = [
        node for node in range(snapshot.node_count)
        if snapshot.node_name(node).startswith("VMRoot[")
    ]
    return {
        "constant_pool_count": len(pools),
        "constant_pool_shallow_bytes": sum(snapshot.self_size(node) for node in pools),
        "vm_root_count": len(vm_roots),
        "vm_root_names": [snapshot.node_name(node) for node in vm_roots],
        "sub_a_unique_direct_string_count": len(strings),
        "sub_a_direct_string_edges": string_edges,
        "sub_a_unique_string_data_bytes": sum(snapshot.self_size(node) for node in strings),
        "sub_a_observed_cross_vm_duplicate_gross_bytes": 0 if len(vm_roots) <= 1 else None,
        "sub_a_note": "string self_size is payload length in this translator, not complete aligned string object size; a single VM root cannot measure cross-VM duplication",
        "sub_b_direct_literal_target_counts": dict(direct_literal_target_names),
        "sub_b_direct_literal_target_count": len(direct_literal_targets),
        "sub_b_direct_literal_edges": direct_literal_edges,
        "sub_b_direct_literal_target_shallow_bytes": sum(
            snapshot.self_size(node) for node in direct_literal_targets
        ),
        "sub_b_direct_literal_unique_backing_count": len(direct_literal_backings),
        "sub_b_direct_literal_backing_edges": direct_literal_backing_edges,
        "sub_b_direct_literal_unique_backing_shallow_bytes": sum(
            snapshot.self_size(node) for node in direct_literal_backings
        ),
        "sub_b_direct_literal_resident_bytes": (
            sum(snapshot.self_size(node) for node in direct_literal_targets)
            + sum(snapshot.self_size(node) for node in direct_literal_backings)
        ),
        "sub_b_direct_literal_note": "direct ConstantPool element targets and their Properties/Elements backings are an observable resident set, not attributable literal-COW benefit because clone/write provenance is absent",
        "sub_b_generic_object_array_counts": dict(object_array_names),
        "sub_b_generic_object_array_count": len(object_array_nodes),
        "sub_b_generic_object_array_shallow_bytes": sum(
            snapshot.self_size(node) for node in object_array_nodes
        ),
        "sub_b_generic_unique_backing_count": len(backings),
        "sub_b_generic_backing_edges": backing_edges,
        "sub_b_generic_unique_backing_shallow_bytes": sum(
            snapshot.self_size(node) for node in backings
        ),
        "sub_b_generic_resident_universe_bytes": (
            sum(snapshot.self_size(node) for node in object_array_nodes)
            + sum(snapshot.self_size(node) for node in backings)
        ),
        "sub_b_note": "the translator does not preserve ordinary JSObject/JSArray creation provenance; this generic resident universe is not attributable literal-COW benefit",
        "net_bytes": None,
        "confidence": "low for benefit: worker abc overlap and literal clone/write rates require the existing runtime instrumentation",
    }


def native_interop_census(snapshot: Snapshot) -> dict[str, Any]:
    method_users: dict[int, list[int]] = collections.defaultdict(list)
    for node in range(snapshot.node_count):
        if snapshot.node_type(node) != "closure":
            continue
        method = named_target(snapshot, node, "Method")
        if method is not None:
            method_users[method].append(node)
    shared_stub_closures = {
        closure
        for users in method_users.values()
        if len(users) >= 1000
        for closure in users
    }

    pointer_for: dict[int, int] = {}
    for closure in shared_stub_closures:
        pointers = [
            edge.target for edge in snapshot.outgoing(closure)
            if edge.label == "HashField" and snapshot.node_name(edge.target) == "JSNativePointer"
        ]
        if len(pointers) == 1:
            pointer_for[closure] = pointers[0]

    instance_counts: collections.Counter[int] = collections.Counter()
    prototype_hclasses: dict[int, set[int]] = collections.defaultdict(set)
    for node in range(snapshot.node_count):
        for edge in snapshot.outgoing(node):
            if edge.label == "hclass":
                instance_counts[edge.target] += 1
            if snapshot.node_name(node) == HCLASS_NAME and edge.label == "Proto":
                prototype_hclasses[edge.target].add(node)

    zero_instance_prototypes = {
        prototype
        for prototype, hclasses in prototype_hclasses.items()
        if hclasses and all(instance_counts[hclass] == 0 for hclass in hclasses)
    }

    # Method-only structural upper bound aligned with the Top13 24.035 MiB
    # Kuaishou scope: shared native-stub closures retained directly by
    # zero-instance prototypes, with class constructors reported separately.
    # API 26 translator output exposes the property name on the prototype edge,
    # while the older Top13 output used an InlineProperty identity edge.
    method_scope_pairs: list[tuple[int, str, int]] = []
    constructor_scope_pairs: list[tuple[int, str, int]] = []
    for prototype in zero_instance_prototypes:
        for edge in snapshot.outgoing(prototype):
            if edge.edge_type != "property" or edge.target not in shared_stub_closures:
                continue
            pair = (prototype, str(edge.label), edge.target)
            if edge.label == "constructor":
                constructor_scope_pairs.append(pair)
            else:
                method_scope_pairs.append(pair)

    method_scope_closures = {closure for _, _, closure in method_scope_pairs}
    constructor_scope_closures = {closure for _, _, closure in constructor_scope_pairs}
    overlap = method_scope_closures & constructor_scope_closures
    if overlap:
        raise ValueError(f"native interop method/constructor overlap: {len(overlap)}")
    all_scope_closures = method_scope_closures | constructor_scope_closures
    method_scope_bytes = sum(snapshot.self_size(closure) for closure in method_scope_closures)
    constructor_scope_bytes = sum(
        snapshot.self_size(closure) for closure in constructor_scope_closures
    )
    all_scope_bytes = sum(snapshot.self_size(closure) for closure in all_scope_closures)
    if len(method_scope_closures) + len(constructor_scope_closures) != len(all_scope_closures):
        raise ValueError("native interop population conservation failed")
    if method_scope_bytes + constructor_scope_bytes != all_scope_bytes:
        raise ValueError("native interop byte conservation failed")

    pairs: list[tuple[int, str, int]] = []
    for prototype, label, closure in method_scope_pairs:
        if closure in pointer_for:
            pairs.append((prototype, label, closure))

    closures = {closure for _, _, closure in pairs}
    pointers = {pointer_for[closure] for closure in closures}
    property_slots = len(pairs)
    known_heap_gross = (
        sum(snapshot.self_size(closure) for closure in closures)
        + sum(snapshot.self_size(pointer) for pointer in pointers)
    )
    external_low = 32 * len(closures)
    external_high = 40 * len(closures)
    descriptor_low = 72 * property_slots
    descriptor_high = 96 * property_slots
    return {
        "shared_native_stub_closure_population": len(shared_stub_closures),
        "zero_live_instance_prototype_count": len(zero_instance_prototypes),
        "method_only_structural_upper_bound": {
            "candidate_prototype_count": len(
                {prototype for prototype, _, _ in method_scope_pairs}
            ),
            "method_property_slots": len(method_scope_pairs),
            "method_closure_population": len(method_scope_closures),
            "method_closure_shallow_bytes": method_scope_bytes,
            "method_closure_shallow_mib": method_scope_bytes / MIB,
            "constructor_property_slots": len(constructor_scope_pairs),
            "constructor_closure_population": len(constructor_scope_closures),
            "constructor_closure_shallow_bytes": constructor_scope_bytes,
            "constructor_closure_shallow_mib": constructor_scope_bytes / MIB,
            "combined_closure_population": len(all_scope_closures),
            "combined_closure_shallow_bytes": all_scope_bytes,
            "combined_closure_shallow_mib": all_scope_bytes / MIB,
            "top_property_names": collections.Counter(
                label for _, label, _ in method_scope_pairs
            ).most_common(30),
            "scope": "method-only structural upper bound aligned with the Top13 24.035 MiB semantic scope: unique shared-native-stub closures held by zero-live-instance prototypes, excluding constructor; API 26 property-edge labels replace the older translator's InlineProperty identity edges",
            "confidence": "low for realized benefit: zero live instances do not prove that a class or method was never read or called; runtime instrumentation remains mandatory",
        },
        "structural_candidate_prototype_count": len({prototype for prototype, _, _ in pairs}),
        "structural_candidate_property_slots": property_slots,
        "structural_candidate_unique_closures": len(closures),
        "structural_candidate_unique_native_pointers": len(pointers),
        "closure_shallow_bytes": sum(snapshot.self_size(closure) for closure in closures),
        "native_pointer_shallow_bytes": sum(snapshot.self_size(pointer) for pointer in pointers),
        "known_heap_gross_bytes": known_heap_gross,
        "modeled_napi_function_info_bytes": {"low": external_low, "high": external_high},
        "modeled_descriptor_cost_bytes": {"low": descriptor_low, "high": descriptor_high},
        "modeled_net_bytes": {
            "low": known_heap_gross + external_low - descriptor_high,
            "high": known_heap_gross + external_high - descriptor_low,
        },
        "top_property_names": collections.Counter(label for _, label, _ in pairs).most_common(30),
        "scope": "strict A2 subset only: method-only structural upper bound further restricted to closures with exactly one visible JSNativePointer",
        "confidence": "low for realized benefit: full-GC liveness does not prove a method was never read or called; runtime read/call instrumentation remains mandatory",
    }


def sample_census(snapshot: Snapshot) -> dict[str, Any]:
    return {
        "snapshot": snapshot.metadata(),
        "jshclass_auxdata_sidecar": jshclass_census(snapshot),
        "layoutinfo_attr_packing": layoutinfo_census(snapshot),
        "profile_type_info_cell": profile_cell_census(snapshot),
        "profile_type_info": profile_type_info_census(snapshot),
        "jitfree_adjacent_layout": jitfree_adjacent_layout_census(snapshot),
        "constantpool_shared_literal": constantpool_census(snapshot),
        "native_interop_lazy_binding": native_interop_census(snapshot),
    }


def numeric_delta(foreground: Any, background: Any) -> Any:
    if isinstance(foreground, dict) and isinstance(background, dict):
        return {
            key: numeric_delta(foreground[key], background[key])
            for key in foreground.keys() & background.keys()
            if isinstance(foreground[key], (int, float, dict))
            and isinstance(background[key], (int, float, dict))
        }
    if isinstance(foreground, (int, float)) and isinstance(background, (int, float)):
        return background - foreground
    return None


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--foreground-rawheap", required=True)
    parser.add_argument("--foreground-snapshot", required=True)
    parser.add_argument("--foreground-object-count", required=True, type=int)
    parser.add_argument("--background-rawheap", required=True)
    parser.add_argument("--background-snapshot", required=True)
    parser.add_argument("--background-object-count", required=True, type=int)
    parser.add_argument("--translator", required=True)
    parser.add_argument("--output")
    args = parser.parse_args()

    translator = file_record(args.translator)
    version = subprocess.run(
        [args.translator, "--version"], check=True, text=True, capture_output=True
    ).stdout.strip()
    translator["version"] = version

    foreground_snapshot = Snapshot(args.foreground_snapshot)
    foreground = sample_census(foreground_snapshot)
    del foreground_snapshot
    background_snapshot = Snapshot(args.background_snapshot)
    background = sample_census(background_snapshot)
    del background_snapshot

    result = {
        "schema_version": 2,
        "units": {"MiB": 1048576, "MB": 1000000},
        "scope": {
            "application": "kuaishou",
            "comparison": "paired foreground conservative-GC vs background full-GC",
            "rule": "samples are reported separately; no Top13 scaling and no foreground/background population mixing",
            "source_revisions": {
                "ets_runtime": "4ad6583a30981259b857579c61b5cc83b3530381",
                "runtime_core": "ed8cec5810e2ae37d4972f501ff189c82d1db6a8",
            },
        },
        "translator": translator,
        "foreground_rawheap": {
            **file_record(args.foreground_rawheap),
            "protocol": rawheap_protocol(args.foreground_rawheap),
            "translator_reported_object_count": args.foreground_object_count,
        },
        "background_rawheap": {
            **file_record(args.background_rawheap),
            "protocol": rawheap_protocol(args.background_rawheap),
            "translator_reported_object_count": args.background_object_count,
            "collection_context": "application background; user states full GC was performed",
        },
        "foreground": foreground,
        "background": background,
        "background_minus_foreground": numeric_delta(foreground, background),
        "interpretation_limits": [
            "Full GC improves confidence that background nodes are live at capture time; it does not imply every proposal has a larger absolute benefit.",
            "A snapshot does not record future first feedback, native property reads/calls, worker abc overlap, or literal clone/write history.",
            "Snapshot self_size is shallow size. String self_size from this translator is payload length rather than full aligned string-object size.",
            "External allocator fragmentation, Region slack, RSS/PSS, and GC pause changes require implementation A/B measurements.",
        ],
    }

    text = json.dumps(result, ensure_ascii=False, indent=2, sort_keys=True) + "\n"
    if args.output:
        with open(args.output, "w", encoding="utf-8", newline="\n") as stream:
            stream.write(text)
    else:
        print(text, end="")


if __name__ == "__main__":
    main()
